# Generated by Django 4.2.7 on 2023-12-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='question_text',
            field=models.CharField(max_length=1000),
        ),
    ]
